sudo: false
language: ruby
rvm: 2.3.1
# rvm:
#   - 2.0.0
#   - 2.1.3
#   - 2.2.0
# env:
#   - DB=sqlite
#   - DB=mysql
cache: bundler
before_script:
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script:
  - RAILS_ENV=test bundle exec rspec
