language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
cache: bundler
before_script:
  - cp test/app/config/database.travis.yml test/app/config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
script:
  - RAILS_ENV=test bundle exec rake test
notifications:
  email:
    - deanpcmad@gmail.com
  hipchat:
    rooms:
      secure: HlW0xg8sQ34956CmAO0SGWt8ERR+QzzpnUFhlM8ouAUsX6W0/KCmcH3cF275aP2xpVAL2qwipVOjLBsMtdYtOzZR9rcj2P/NiTngxK2c+iR6HfkJgMO2TKuVIc39EenxyZUOKwWJHZf/wCn926hwvn8AUjgEfeabwp4mPlyErYU=
